pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: squash
        
  - name: automatic merge on CI success
    conditions:
      - status-success=Travis CI - Pull Request
      - author=Leocardoso94
    actions:
      merge:
        method: squash
  
  - name: merge pull requests from dependabot if CI passes
    conditions:
      - author=dependabot-preview[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash
